import type { GapFillJobSnapshot } from './types.ts'

/** 空き枠埋め用ワンショットプロンプト（近接優先・チャット風依頼） */
export function buildGapFillPrompt(snapshot: GapFillJobSnapshot): string {
  const payload = JSON.stringify(
    {
      mode: snapshot.mode,
      targetDate: snapshot.targetDate,
      windowStart: snapshot.windowStart,
      windowEnd: snapshot.windowEnd,
      preferredTeamIndex: snapshot.preferredTeamIndex,
      travelGapMinutes: snapshot.travelGapMinutes,
      anchorPatientIds: snapshot.anchorPatientIds,
      teams: snapshot.teams,
      patients: snapshot.patients.map((patient) => ({
        patientId: patient.patientId,
        areaLabel: patient.areaLabel,
        facilityId: patient.facilityId,
        durationMinutes: patient.durationMinutes,
        preferredWeekdays: patient.preferredWeekdays,
        priority: patient.priority,
        dueStatus: patient.dueStatus,
        dueUrgencyDays: patient.dueUrgencyDays,
        gapProximityMinutes: patient.gapProximityMinutes,
      })),
      existingVisits: snapshot.existingVisits,
      travelMinutesMatrix: snapshot.travelMinutesMatrix,
    },
    null,
    2,
  )

  return [
    'あなたは訪問歯科の空き枠埋めアシスタントです。',
    'Supabase / DB / 外部 API / 地図 API には一切接続しないでください。',
    '以下の JSON スナップショットだけを根拠に、指定の空き枠へ入れられる候補を提案してください。',
    '',
    `利用者の依頼: ${snapshot.userMessage}`,
    '',
    '最重要（提案の並び）:',
    '- **住所・ルートの近さ（gapProximityMinutes / travelMinutesMatrix）を最優先**する',
    '- gapProximityMinutes が小さい患者から最大件数まで必ず候補を出す',
    '- dueStatus や希望曜日は二次条件。期限が遠くても近い人は warnings 付きで返す',
    '- 「本当に無理」な場合だけ除外（窓に所要が全く入らない・スナップショット外 ID など）',
    '- 候補が1人でもいるなら { "slots": [] } を返さない',
    '',
    '制約:',
    `- 対象日: ${snapshot.targetDate}`,
    `- 空き枠: ${snapshot.windowStart} 〜 ${snapshot.windowEnd}`,
    `- 優先号車 teamIndex: ${snapshot.preferredTeamIndex}`,
    `- 最大候補数: ${snapshot.maxSlots}`,
    `- 最低移動ギャップ: ${snapshot.travelGapMinutes} 分（同一チームの前後枠との関係）`,
    '- existingVisits は当日の既存枠。同じ teamIndex で時間が重なる提案は禁止',
    '- anchorPatientIds は空き枠前後の既存訪問。これらへの移動分が小さいほど良い',
    '- patientId はスナップショットに存在する ID のみ',
    '- proposedStart / proposedEnd は空き枠内に収める',
    '- 生の住所文字列は渡していない',
    '',
    '出力は次の JSON オブジェクトだけ（前後に説明文やコードフェンスを付けない）:',
    '{',
    '  "slots": [',
    '    {',
    '      "patientId": "<uuid>",',
    '      "proposedStart": "HH:mm:ss",',
    '      "proposedEnd": "HH:mm:ss",',
    '      "teamIndex": 0,',
    '      "reason": "短い日本語理由（近接に触れる）",',
    '      "warnings": ["条件外の短い注意（任意）"]',
    '    }',
    '  ]',
    '}',
    '',
    '=== スナップショット ===',
    payload,
  ].join('\n')
}
